/*
 * SPDX-License-Identifier: Apache-2.0
 * ML-DSA-44 NTT engine known-answer tests (FIPS 204 §4.2, Algorithm 41–44).
 *
 * Test vectors generated by compiling and executing the pq-crystals/dilithium
 * reference implementation (ref/ntt.c, ref/reduce.c) with gcc on macOS arm64,
 * then capturing the output as known-answer test vectors. These cover:
 *
 * - The 256-entry zetas table (Montgomery form: zetas[i] = ζ_i * 2^32 mod Q)
 * - montgomeryReduce on edge-case scalar inputs
 * - reduce32 / caddq / freeze boundary values
 * - NTT forward transform on all-ones and sequential polynomials
 * - NTT→inverse-NTT round-trip (property test, including random coefficients)
 * - Pointwise Montgomery multiply then inverse NTT
 *
 * The zetas are in Montgomery form so that the forward NTT butterfly
 * `t = montgomeryReduce(zeta * a[j + len])` produces `t = ζ * a[j + len] mod Q`
 * directly, without a separate modular reduction.
 *
 * References:
 *   - FIPS 204 §4.2 (NTT, inverse NTT, MLDSA zetas)
 *   - pq-crystals/dilithium ref/ntt.c, ref/reduce.c
 *   - Wycheproof ML-DSA-44 test vectors (end-to-end verify in MLDSA44Test.kt)
 */
package ch.trancee.meshlink.crypto

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Tag

internal class MLDSANttTest {

  // ------------------------------------------------------------------
  // Zetas table — 256 Montgomery-form roots ζ_i * 2^32 mod Q
  // ------------------------------------------------------------------

  @Tag("critical-path")
  @Tag("positive")
  @Test
  fun `zetas table matches Dilithium reference`() {
    val expected = MLDSANtt.zetas
    assertEquals(256, expected.size, "zetas table must have 256 entries (index 0..255)")

    // Spot-check critical values from ref/ntt.c
    assertEquals(0, expected[0], "zetas[0] must be 0")
    assertEquals(25847, expected[1], "zetas[1] must be 25847")
    assertEquals(-2608894, expected[2])
    assertEquals(1826347, expected[8])
    assertEquals(-3861115, expected[40])
    assertEquals(1976782, expected[255], "zetas[255] must match ref/ntt.c")

    // Every zeta must be in centered representative range [-Q/2, Q/2)
    val q = MLDSANtt.Q
    for (i in expected.indices) {
      assertTrue(
          expected[i] >= -(q - 1) / 2 && expected[i] <= q / 2,
          "zetas[$i] = ${expected[i]} must be in centered representative range",
      )
    }
  }

  // ------------------------------------------------------------------
  // montgomeryReduce — reduces 64-bit product to 32-bit field element
  // r ≡ a * R^(-1) (mod Q) where R = 2^32, for |a| ≤ 2^31·Q
  // ------------------------------------------------------------------

  @Tag("critical-path")
  @Tag("positive")
  @Test
  fun `montgomeryReduce on known-answer vectors`() {
    assertEquals(1822058, MLDSANtt.montgomeryReduce(1_000_000L))
    assertEquals(114592, MLDSANtt.montgomeryReduce(-1L))
    assertEquals(0, MLDSANtt.montgomeryReduce(8380417L))
  }

  @Tag("critical-path")
  @Tag("positive")
  @Test
  fun `montgomeryReduce of zero is zero`() {
    assertEquals(0, MLDSANtt.montgomeryReduce(0L))
  }

  // ------------------------------------------------------------------
  // reduce32 — lazy Barrett-like reduction to [-(3/4)Q, (3/4)Q]
  // ------------------------------------------------------------------

  @Tag("critical-path")
  @Tag("positive")
  @Test
  fun `reduce32 on known-answer vectors`() {
    assertEquals(0, MLDSANtt.reduce32(0))
    assertEquals(1, MLDSANtt.reduce32(1))
    assertEquals(-1, MLDSANtt.reduce32(-1))
    assertEquals(0, MLDSANtt.reduce32(8380417))
    assertEquals(0, MLDSANtt.reduce32(16760834)) // 2*Q → 0
    assertEquals(0, MLDSANtt.reduce32(-8380417))
  }

  @Tag("critical-path")
  @Tag("positive")
  @Test
  fun `reduce32 produces output within valid bounds`() {
    val bound = 6283008 // (3/4) * Q
    for (v in listOf(0, 1, -1, 8380417, -8380417, 1234567, -9876543, 100000000, -200000000)) {
      val r = MLDSANtt.reduce32(v)
      assertTrue(r >= -bound && r <= bound, "reduce32($v)=$r must be in [-6283008, 6283008]")
    }
  }

  // ------------------------------------------------------------------
  // caddq — adds Q to negative values via arithmetic right shift
  // ------------------------------------------------------------------

  @Tag("critical-path")
  @Tag("positive")
  @Test
  fun `caddq adds Q to negative values`() {
    assertEquals(0, MLDSANtt.caddq(0))
    assertEquals(8380416, MLDSANtt.caddq(-1))
    assertEquals(0, MLDSANtt.caddq(-8380417))
  }

  @Tag("critical-path")
  @Tag("positive")
  @Test
  fun `caddq is identity for non-negative in-range values`() {
    assertEquals(8380416, MLDSANtt.caddq(8380416))
    assertEquals(4190208, MLDSANtt.caddq(4190208))
  }

  // ------------------------------------------------------------------
  // freeze — reduce32 + caddq → [0, Q-1]
  // ------------------------------------------------------------------

  @Tag("critical-path")
  @Tag("positive")
  @Test
  fun `freeze maps to standard representative range`() {
    assertEquals(0, MLDSANtt.freeze(0))
    assertEquals(8380416, MLDSANtt.freeze(-1))
    assertEquals(8380416, MLDSANtt.freeze(8380416))
    assertEquals(0, MLDSANtt.freeze(8380417))
  }

  @Tag("critical-path")
  @Tag("positive")
  @Test
  fun `freeze handles wraparound values`() {
    assertEquals(0, MLDSANtt.freeze(-8380417)) // -Q → 0
    assertEquals(5, MLDSANtt.freeze(8380422)) // Q+5 → 5
    assertEquals(8380412, MLDSANtt.freeze(-5)) // -5 → Q-5
  }

  // ------------------------------------------------------------------
  // NTT forward — known-answer tests from C reference
  // ------------------------------------------------------------------

  private fun polyOnes(): IntArray = IntArray(256) { 1 }

  private fun polySeq(): IntArray = IntArray(256) { it }

  @Tag("critical-path")
  @Tag("positive")
  @Test
  fun `ntt transforms all-ones polynomial to known values`() {
    val a = polyOnes()
    MLDSANtt.ntt(a)
    assertEquals(-3778841, a[0])
    assertEquals(-8294415, a[1])
    assertEquals(-8559169, a[2])
    assertEquals(-10440159, a[3])
    assertEquals(-15254905, a[8])
    assertEquals(-21836976, a[28])
  }

  @Tag("critical-path")
  @Tag("positive")
  @Test
  fun `ntt transforms sequential polynomial to known values`() {
    val a = polySeq()
    MLDSANtt.ntt(a)
    assertEquals(-356594, a[0])
    assertEquals(4949942, a[1])
    assertEquals(13884114, a[2])
    assertEquals(7227518, a[3])
    assertEquals(8329041, a[20])
    assertEquals(2296483, a[21])
  }

  // ------------------------------------------------------------------
  // NTT round-trip: invnttTomont recovers original (mod Q)
  // ------------------------------------------------------------------

  private fun modQ(v: Int): Int {
    val q = MLDSANtt.Q
    return ((v % q) + q) % q
  }

  @Tag("critical-path")
  @Tag("positive")
  @Test
  fun `ntt then invnttTomont recovers original all-ones polynomial in Montgomery form`() {
    val a = polyOnes()
    MLDSANtt.ntt(a)
    MLDSANtt.invnttTomont(a)
    // After NTT → invNTT, result = original * MONT mod Q in Montgomery domain
    // For input 1, output = MONT mod Q = 4193792 (or -4186625 signed)
    val montMod = modQ(MLDSANtt.MONT)
    for (i in a.indices) {
      assertEquals(montMod, modQ(a[i]), "coeff[$i] after round-trip must be MONT mod Q")
    }
  }

  @Tag("critical-path")
  @Tag("positive")
  @Test
  fun `ntt then invnttTomont recovers sequential polynomial in Montgomery form`() {
    val a = polySeq()
    MLDSANtt.ntt(a)
    MLDSANtt.invnttTomont(a)
    // For input i, output = i * MONT mod Q
    val q = MLDSANtt.Q
    val mont = 4193792 // 2^32 mod Q
    for (i in a.indices) {
      val expected = modQ((i.toLong() * mont % q).toInt())
      assertEquals(expected, modQ(a[i]), "coeff[$i] after round-trip must be i*MONT mod Q")
    }
  }

  // ------------------------------------------------------------------
  // Pointwise multiply: NTT(a) ⊙ NTT(b) → invNTT
  // For a=b=ones in the ring, a*b = 256*ones mod (x^256 - 1)
  // After invntt, result is 256 * MONT mod Q in Montgomery domain
  // ------------------------------------------------------------------

  @Tag("critical-path")
  @Tag("positive")
  @Test
  fun `pointwise Monty multiply of NTT of ones with itself`() {
    val a = polyOnes()
    val b = polyOnes()
    MLDSANtt.ntt(a)
    MLDSANtt.ntt(b)
    val res = IntArray(256)
    for (i in res.indices) {
      res[i] = MLDSANtt.montgomeryReduce(a[i].toLong() * b[i])
    }
    MLDSANtt.invnttTomont(res)
    // C reference gives -254, -252, -250, -248, ... (256 * MONT mod Q, varying by index)
    assertEquals(-254, res[0], "pointwise(ones, ones)[0] must match C reference")
    assertEquals(-252, res[1])
    assertEquals(-250, res[2])
    assertEquals(-248, res[3])
    assertEquals(-240, res[7])
  }

  // ------------------------------------------------------------------
  // Property test: random polynomials round-trip through NTT/invNTT
  // ------------------------------------------------------------------

  @Tag("critical-path")
  @Tag("positive")
  @Test
  fun `random polynomial NTT round-trip preserves values mod Q`() {
    val q = MLDSANtt.Q
    val mont = 4193792L // 2^32 mod Q (Montgomery factor)
    val rng = java.util.Random(0xCAFEBABE)

    repeat(10) { seed ->
      val a = IntArray(256)
      for (i in a.indices) {
        a[i] = rng.nextInt(q) - q / 2 // centered in [-Q/2, Q/2)
      }
      // expected[i] = a[i] * MONT mod Q
      val expected = IntArray(256) { i -> modQ((a[i].toLong() * mont % q).toInt()) }

      MLDSANtt.ntt(a)
      MLDSANtt.invnttTomont(a)

      for (i in a.indices) {
        assertEquals(
            expected[i],
            modQ(a[i]),
            "round-trip mod Q failed at coeff[$i] with seed=$seed",
        )
      }
    }
  }
}
