/*
 * SPDX-License-Identifier: Apache-2.0
 * Shared Keccak-f[1600] permutation engine used by all Keccak/XOF primitives
 * in this library (SHAKE128, SHAKE256, SHA3-256, SHA3-512).
 *
 * The permutation is identical across all Keccak-based primitives — only the
 * sponge rate and domain-separation suffix differ (see FIPS 202 §8).
 *
 * Round constants are generated by the 7-bit LFSR (polynomial 0x71) per the
 * [XKCP](https://github.com/XKCP/XKCP) TweetableFIPS202 reference
 * (TweetableFIPS202.c). Verified to produce the canonical Keccak-f[1600]
 * zero-state output lane[0] = 0xF1258F7940E1DDE7 and parameters against
 * XKCP SimpleFIPS202.c (SHAKE128 rate=1344/capacity=256/suffix=0x1F;
 * SHAKE256 rate=1088/capacity=512/suffix=0x1F).
 */
package ch.trancee.meshlink.crypto

/**
 * Combines a high 32-bit half [hi] and a low 32-bit half [lo] into a 64-bit Long.
 *
 * Kotlin disallows hex Long literals whose unsigned value exceeds Long.MAX_VALUE (high bit set), so
 * each round constant is assembled from two 32-bit hex halves.
 */
internal fun keccakL(hi: Long, lo: Long): Long = (hi shl 32) or (lo and 0xFFFFFFFFL)

/**
 * Keccak-f[1600] round constants (24 values, one per round).
 *
 * Each is a 64-bit lane XORed into position (0,0) during the iota step. Constants with the high bit
 * set use [keccakL] to bypass Kotlin's signed-Long hex literal restriction. Values match the
 * [XKCP](https://github.com/XKCP/XKCP) TweetableFIPS202 LFSR generator.
 */
internal val KeccakRoundConstants: LongArray =
    longArrayOf(
        keccakL(0x00000000L, 0x00000001L),
        keccakL(0x00000000L, 0x00008082L),
        keccakL(0x80000000L, 0x0000808aL),
        keccakL(0x80000000L, 0x80008000L),
        keccakL(0x00000000L, 0x0000808bL),
        keccakL(0x00000000L, 0x80000001L),
        keccakL(0x80000000L, 0x80008081L),
        keccakL(0x80000000L, 0x00008009L),
        keccakL(0x00000000L, 0x0000008aL),
        keccakL(0x00000000L, 0x00000088L),
        keccakL(0x00000000L, 0x80008009L),
        keccakL(0x00000000L, 0x8000000aL),
        keccakL(0x00000000L, 0x8000808bL),
        keccakL(0x80000000L, 0x0000008bL),
        keccakL(0x80000000L, 0x00008089L),
        keccakL(0x80000000L, 0x00008003L),
        keccakL(0x80000000L, 0x00008002L),
        keccakL(0x80000000L, 0x00000080L),
        keccakL(0x00000000L, 0x0000800aL),
        keccakL(0x80000000L, 0x8000000aL),
        keccakL(0x80000000L, 0x80008081L),
        keccakL(0x80000000L, 0x00008080L),
        keccakL(0x00000000L, 0x80000001L),
        keccakL(0x80000000L, 0x80008008L),
    )

/**
 * Keccak-f[1600] rho rotation offsets.
 *
 * Indexed as [x][y] (first index = x-coordinate, second index = y-coordinate), so lane (x, y) is
 * rotated left by [KeccakRotationConstants[x][y]] bits before being placed into its new position by
 * pi.
 */
internal val KeccakRotationConstants: Array<IntArray> =
    arrayOf(
        intArrayOf(0, 36, 3, 41, 18), // x=0
        intArrayOf(1, 44, 10, 45, 2), // x=1
        intArrayOf(62, 6, 43, 15, 61), // x=2
        intArrayOf(28, 55, 25, 21, 56), // x=3
        intArrayOf(27, 20, 39, 8, 14), // x=4
    )

/**
 * Rotates [v] left by [n] bits using (v shl n) or (v ushr (64 - n)).
 *
 * For n = 0, the shift amounts are 0 and 64; Kotlin's shift semantics reduce the right operand
 * modulo 64 for Long, so ushr(64) is equivalent to ushr(0).
 */
internal fun keccakRol64(v: Long, n: Int): Long = (v shl n) or (v ushr (64 - n))

/**
 * Applies the Keccak-f[1600] permutation to [state] (25 x 64-bit lanes).
 *
 * 24 rounds of theta, rho+pi, chi, and iota — no data-dependent branching or indexing, so execution
 * time is independent of message content (ADR-0001, ADR-0003).
 */
internal fun keccakF1600(state: LongArray) {
  for (round in 0 until 24) {
    // θ — column parity diffusion
    val c = LongArray(5)
    for (x in 0..4) {
      c[x] = state[x] xor state[x + 5] xor state[x + 10] xor state[x + 15] xor state[x + 20]
    }
    val d = LongArray(5)
    for (x in 0..4) {
      d[x] = c[(x + 4) % 5] xor keccakRol64(c[(x + 1) % 5], 1)
    }
    for (x in 0..4) {
      for (y in 0..4) {
        state[x + 5 * y] = state[x + 5 * y] xor d[x]
      }
    }

    // ρ + π — bit-rotation + lane permutation
    val newState = LongArray(25)
    for (x in 0..4) {
      for (y in 0..4) {
        val oldX = (3 * y + x) % 5
        newState[x + 5 * y] = keccakRol64(state[oldX + 5 * x], KeccakRotationConstants[oldX][x])
      }
    }
    for (i in 0..24) state[i] = newState[i]

    // χ — non-linear layer
    for (y in 0..4) {
      val base = 5 * y
      val row = LongArray(5)
      for (x in 0..4) row[x] = state[base + x]
      for (x in 0..4) {
        state[base + x] = row[x] xor (row[(x + 1) % 5].inv() and row[(x + 2) % 5])
      }
    }

    // ι — round-constant injection into lane (0, 0)
    state[0] = state[0] xor KeccakRoundConstants[round]
  }
}
