/*
 * SPDX-License-Identifier: Apache-2.0
 * ML-DSA-44 NTT engine (FIPS 204 §4.2, Algorithms 41–44).
 *
 * Pure-Kotlin implementation of the Number-Theoretic Transform over Z_q with q = 8380417.
 * All reduction paths are branch-free on secret data (ADR-0003):
 * - montgomeryReduce uses 64-bit word arithmetic with no secret-dependent branches
 * - reduce32 uses a single arithmetic right-shift (FIPS 204 Algorithm 44)
 * - caddq uses arithmetic right-shift by 31 to produce a 0/Q mask
 * - ntt/invnttTomont use the standard CTC / GS butterfly with no conditional branches
 *
 * The zetas table stores 256 roots of unity in Montgomery form (ζ_i * 2^32 mod Q)
 * so that `montgomeryReduce(zeta * a[j+len])` computes `ζ * a[j+len] mod Q`
 * directly, eliminating a separate modular reduction per butterfly step.
 *
 * Reference: pq-crystals/dilithium ref/ntt.c, ref/reduce.c
 */
package ch.trancee.meshlink.crypto

/**
 * ML-DSA-44 NTT engine: forward NTT, inverse NTT, Montgomery reduction, and constant-time
 * compare/move helpers.
 *
 * All functions here are `internal` — callers operate through [MLDSA44PureK]. The `@Secret`
 * annotation on NTT functions lets the `:crypto-detekt-rules` `ConstantTimeRule` reject any
 * data-dependent branching on secret polynomial coefficients (ADR-0003).
 */
internal object MLDSANtt {

  /** Field modulus Q = 8380417 (FIPS 204 §3, Table 1). */
  const val Q: Int = 8380417

  /** Q^(-1) mod 2^32 = 58728449 (used by Montgomery reduction). */
  private const val QINV: Int = 58728449

  /** 2^32 mod Q = 4193792 = -4186625 (signed). Used to enter/leave Montgomery domain. */
  const val MONT: Int = -4186625

  /** 2^(2*32) / 256 mod Q = 41978 (applied at the end of invnttTomont for normalization). */
  private const val F: Int = 41978

  /** Polynomial degree N = 256 (FIPS 204 §3). */
  private const val N: Int = 256

  /** Number of zetas (index 0 unused; indices 1..255). */
  private const val ZETA_LEN: Int = 256

  // ------------------------------------------------------------------
  // Zetas table — ζ_i * R mod Q where R = 2^32 (Montgomery form)
  // Generated by pq-crystals/dilithium ref/ntt.c init_ntt() logic,
  // values match FIPS 204 Appendix B after Montgomery-domain conversion.
  // ------------------------------------------------------------------

  /**
   * 256 roots of unity in Montgomery form.
   *
   * zetas[0] = 0 (unused); zetas[1..255] are the forward NTT roots ζ_i * R mod Q, where R = 2^32.
   * These match the Dilithium reference implementation's static `zetas[N]` table in ref/ntt.c.
   */
  internal val zetas: IntArray =
      intArrayOf(
          0,
          25847,
          -2608894,
          -518909,
          237124,
          -777960,
          -876248,
          466468,
          1826347,
          2353451,
          -359251,
          -2091905,
          3119733,
          -2884855,
          3111497,
          2680103,
          2725464,
          1024112,
          -1079900,
          3585928,
          -549488,
          -1119584,
          2619752,
          -2108549,
          -2118186,
          -3859737,
          -1399561,
          -3277672,
          1757237,
          -19422,
          4010497,
          280005,
          2706023,
          95776,
          3077325,
          3530437,
          -1661693,
          -3592148,
          -2537516,
          3915439,
          -3861115,
          -3043716,
          3574422,
          -2867647,
          3539968,
          -300467,
          2348700,
          -539299,
          -1699267,
          -1643818,
          3505694,
          -3821735,
          3507263,
          -2140649,
          -1600420,
          3699596,
          811944,
          531354,
          954230,
          3881043,
          3900724,
          -2556880,
          2071892,
          -2797779,
          -3930395,
          -1528703,
          -3677745,
          -3041255,
          -1452451,
          3475950,
          2176455,
          -1585221,
          -1257611,
          1939314,
          -4083598,
          -1000202,
          -3190144,
          -3157330,
          -3632928,
          126922,
          3412210,
          -983419,
          2147896,
          2715295,
          -2967645,
          -3693493,
          -411027,
          -2477047,
          -671102,
          -1228525,
          -22981,
          -1308169,
          -381987,
          1349076,
          1852771,
          -1430430,
          -3343383,
          264944,
          508951,
          3097992,
          44288,
          -1100098,
          904516,
          3958618,
          -3724342,
          -8578,
          1653064,
          -3249728,
          2389356,
          -210977,
          759969,
          -1316856,
          189548,
          -3553272,
          3159746,
          -1851402,
          -2409325,
          -177440,
          1315589,
          1341330,
          1285669,
          -1584928,
          -812732,
          -1439742,
          -3019102,
          -3881060,
          -3628969,
          3839961,
          2091667,
          3407706,
          2316500,
          3817976,
          -3342478,
          2244091,
          -2446433,
          -3562462,
          266997,
          2434439,
          -1235728,
          3513181,
          -3520352,
          -3759364,
          -1197226,
          -3193378,
          900702,
          1859098,
          909542,
          819034,
          495491,
          -1613174,
          -43260,
          -522500,
          -655327,
          -3122442,
          2031748,
          3207046,
          -3556995,
          -525098,
          -768622,
          -3595838,
          342297,
          286988,
          -2437823,
          4108315,
          3437287,
          -3342277,
          1735879,
          203044,
          2842341,
          2691481,
          -2590150,
          1265009,
          4055324,
          1247620,
          2486353,
          1595974,
          -3767016,
          1250494,
          2635921,
          -3548272,
          -2994039,
          1869119,
          1903435,
          -1050970,
          -1333058,
          1237275,
          -3318210,
          -1430225,
          -451100,
          1312455,
          3306115,
          -1962642,
          -1279661,
          1917081,
          -2546312,
          -1374803,
          1500165,
          777191,
          2235880,
          3406031,
          -542412,
          -2831860,
          -1671176,
          -1846953,
          -2584293,
          -3724270,
          594136,
          -3776993,
          -2013608,
          2432395,
          2454455,
          -164721,
          1957272,
          3369112,
          185531,
          -1207385,
          -3183426,
          162844,
          1616392,
          3014001,
          810149,
          1652634,
          -3694233,
          -1799107,
          -3038916,
          3523897,
          3866901,
          269760,
          2213111,
          -975884,
          1717735,
          472078,
          -426683,
          1723600,
          -1803090,
          1910376,
          -1667432,
          -1104333,
          -260646,
          -3833893,
          -2939036,
          -2235985,
          -420899,
          -2286327,
          183443,
          -976891,
          1612842,
          -3545687,
          -554416,
          3919660,
          -48306,
          -1362209,
          3937738,
          1400424,
          -846154,
          1976782,
      )

  // ------------------------------------------------------------------
  // Reduction (FIPS 204 Algorithm 43–44, Dilithium ref/reduce.c)
  // ------------------------------------------------------------------

  /**
   * Montgomery reduction: for `a` in [-2^31·Q, Q·2^31], returns `r ≡ a·R⁻¹ (mod Q)` where R = 2^32,
   * such that -Q < r < Q.
   *
   * Implementation matches Dilithium ref/reduce.c `montgomery_reduce` exactly:
   * ```
   * t = (a & 0xFFFFFFFF) * QINV          // lower 32 bits × Q⁻¹ mod 2³²
   * r = (a - t·Q) >> 32                   // exact division by R = 2³²
   * ```
   *
   * The Kotlin `Long` type provides 64-bit signed two's-complement arithmetic, matching the C
   * `int64_t` behavior.
   */
  internal fun montgomeryReduce(a: Long): Int {
    val t = a.toInt() * QINV
    val r = (a - t.toLong() * Q) shr 32
    return r.toInt()
  }

  /**
   * Barrett-like reduction (FIPS 204 Algorithm 44): for `a` with |a| < 2^31 - 2^22 - 1, returns `r
   * ≡ a (mod Q)` with -6283008 ≤ r ≤ 6283008.
   *
   * This is a *lazy* reduction — the bound 6283008 = (3/4)·Q allows several add/subtract operations
   * before re-reduction is needed, avoiding per-step modular reduction in the NTT butterfly.
   */
  internal fun reduce32(a: Int): Int {
    val t = (a + (1 shl 22)) shr 23
    return a - t * Q
  }

  /**
   * Conditionally adds Q if [a] is negative (branch-free).
   *
   * Uses `a ushr 31` to produce a mask: 0xFFFFFFFF if a < 0, 0x00000000 otherwise. The `&` with Q
   * selects Q (when a < 0) or 0 (when a ≥ 0).
   */
  internal fun caddq(a: Int): Int {
    return a + ((a shr 31) and Q)
  }

  /**
   * Full reduction to the standard representative r = a mod⁺ Q, i.e., r ∈ [0, Q).
   *
   * Combines [reduce32] (lazy reduction to [-3Q/4, 3Q/4]) with [caddq] (shift to [0, Q)).
   */
  internal fun freeze(a: Int): Int {
    val r = reduce32(a)
    return caddq(r)
  }

  // ------------------------------------------------------------------
  // Forward NTT (FIPS 204 Algorithm 41, Dilithium ref/ntt.c `ntt`)
  // ------------------------------------------------------------------

  /**
   * In-place forward NTT (Cooley-Tukey butterfly).
   *
   * Computes the NTT of [a] using the zetas in Montgomery form. After this call, coefficients are
   * in NTT + Montgomery domain. No modular reduction is performed after additions/subtractions —
   * values may grow up to 8Q per coefficient (lazy reduction, the intermediate bounds are safe for
   * int32 arithmetic).
   *
   * @param a coefficient array of length 256; **modified in place**
   */
  internal fun ntt(@Secret a: IntArray) {
    var k = 0
    var length = 128
    while (length > 0) {
      var start = 0
      while (start < N) {
        val zeta = zetas[++k]
        var j = start
        while (j < start + length) {
          val t = montgomeryReduce(zeta.toLong() * a[j + length])
          a[j + length] = a[j] - t
          a[j] = a[j] + t
          j++
        }
        start += length shl 1
      }
      length = length shr 1
    }
  }

  // ------------------------------------------------------------------
  // Inverse NTT + Montgomery normalization (FIPS 204 Algorithm 42)
  // ------------------------------------------------------------------

  /**
   * In-place inverse NTT with Montgomery normalization (Gentleman-Sande butterfly).
   *
   * Recovers coefficients from the NTT + Montgomery domain back to the standard representation.
   * After this call, `result[i] ≡ input[i] · MONT (mod Q)` where MONT = 2^32 mod Q, so coefficients
   * are still in Montgomery form.
   *
   * Input coefficients must be smaller than Q in absolute value. No modular reduction is performed
   * after additions/subtractions (lazy reduction).
   *
   * @param a coefficient array of length 256; **modified in place**
   */
  internal fun invnttTomont(@Secret a: IntArray) {
    var k = N
    var length = 1
    while (length < N) {
      var start = 0
      while (start < N) {
        val zeta = -zetas[--k]
        var j = start
        while (j < start + length) {
          val t = a[j]
          a[j] = t + a[j + length]
          a[j + length] = t - a[j + length]
          a[j + length] = montgomeryReduce(zeta.toLong() * a[j + length])
          j++
        }
        start += length shl 1
      }
      length = length shl 1
    }
    for (j in 0 until N) {
      a[j] = montgomeryReduce(F.toLong() * a[j])
    }
  }
}
